export const dataEquipments = [
  {
    _id: 1,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 2,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 3,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 4,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 5,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 6,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 7,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 8,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 9,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 10,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 11,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 12,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
  {
    _id: 13,
    image: "../assets/images/equipment.png",
    name: "Trinajor runner",
    firm: "Doys Rong",
    usedFor: "Yugurish uchun",
    price: "130 $",
  },
];
