export const dataProducts = [
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
  {
    image: "",
    name: "Whey Protein",
    firm: "PureGold",
    usedFor: "Chocolate Hazelnut",
    price: "11 $",
  },
];
